FROM alpine

RUN apk --no-cache add \
	dovecot \
	dovecot-sqlite \
	dovecot-lmtpd \
	dovecot-pigeonhole-plugin \
	&& rm -rf /etc/dovecot/*

RUN addgroup -g 5000 vmail

RUN adduser -u 5000 -H -h /var/mail -G vmail -D vmail

CMD ["/usr/sbin/dovecot" "-F"]
