FROM debian:12-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -yqq \
	dirmngr \
	ca-certificates \
	gnupg \
	wget \
	&& rm -rf /var/lib/apt/lists/*

#Mono repository
RUN gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
	&& echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/debian stable-buster main" | tee /etc/apt/sources.list.d/mono-official-stable.list

#Media Area repository
RUN wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-21_all.deb && dpkg -i repo-mediaarea_1.0-21_all.deb \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8

#Sonarr repository
RUN	echo "deb https://apt.sonarr.tv/debian buster main" | tee /etc/apt/sources.list.d/sonarr.list

RUN apt update && apt install -yqq \
	sonarr \
	&& rm -rf /var/lib/apt/lists/*

CMD ["/usr/bin/mono", "--debug", "/usr/lib/sonarr/bin/Sonarr.exe", "-nobrowser", "-data=/var/lib/sonarr"]
