FROM debian:12-slim

ENV DEBIAN_FRONTEND noninteractive

# Install necessary packages and clean up the package cache
RUN sed -i 's/Components: main$/Components: main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/debian.sources \
	&& apt update && apt install -yqq \
	7zip \
    wget \
	python3-dev \
	python3-pip \
	python3-setuptools \
	unrar \
	unzip \
	&& rm -rf /var/lib/apt/lists/*

# Create a non-root user for Sonarr and set up its directory
RUN useradd -U --system --no-create-home --shell=/sbin/nologin bazarr

# Download & install Bazarr
RUN wget --content-disposition "https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip" -O bazarr.zip \
    && unzip bazarr.zip -d /opt/bazarr \
    && chown -R bazarr:bazarr /opt/bazarr \
    && rm bazarr.zip \
	&& cd /opt/bazarr \
    && find / -type f -name EXTERNALLY-MANAGED -execdir mv {} EXTERNALLY-MANAGED.bkp \; \
	&& python3 -m pip install -r requirements.txt

USER bazarr
WORKDIR /opt/bazarr

CMD ["/usr/bin/python3", "bazarr.py", "-no-update", "--config", "/config"]
