FROM debian:12-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -yqq \
	postfix \
	postfix-sqlite \
	postfix-policyd-spf-python \
	&& rm -rf /var/lib/apt/lists/*

CMD ["/usr/sbin/postfix" "start-fg"]
