FROM debian:12-slim

ENV DEBIAN_FRONTEND noninteractive

# Install necessary packages and clean up the package cache
RUN apt update && apt install -yqq \
	curl \
	sqlite3 \
	wget \
    libicu-dev \
	&& rm -rf /var/lib/apt/lists/*

# Create a non-root user for Sonarr and set up its directory
RUN useradd -U --system --no-create-home --shell=/sbin/nologin sonarr \
	&& mkdir /var/lib/sonarr \
    && chown sonarr:sonarr /var/lib/sonarr

# Determine and download the appropriate Sonarr release based on architecture
RUN ARCH=$(dpkg --print-architecture) \
    && DLBASE="https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux" \
    && case "$ARCH" in \
        "amd64") DLURL="${DLBASE}&arch=x64" ;; \
        "armhf") DLURL="${DLBASE}&arch=arm" ;; \
        "arm64") DLURL="${DLBASE}&arch=arm64" ;; \
        *) \
            echo "Architecture non prise en charge: $ARCH" \
            && exit 1 \
            ;; \
        esac \
    && wget --content-disposition "$DLURL" -O sonarr.tar.gz \
    && tar -xzf sonarr.tar.gz -C /opt/ \
    && chown -R sonarr:sonarr /opt/Sonarr \
    && rm sonarr.tar.gz

USER sonarr
WORKDIR /opt/Sonarr

CMD ["/opt/Sonarr/Sonarr", "-nobrowser", "-data=/var/lib/sonarr"]
