FROM debian:12-slim

ENV DEBIAN_FRONTEND noninteractive

# Install necessary packages and clean up the package cache
RUN apt update && apt install -yqq \
	curl \
	sqlite3 \
	wget \
    libicu-dev \
	&& rm -rf /var/lib/apt/lists/*

# Create a non-root user for Radarr and set up its directory
RUN useradd -U --system --no-create-home --shell=/sbin/nologin radarr \
	&& mkdir /var/lib/radarr \
    && chown radarr:radarr /var/lib/radarr

# Determine and download the appropriate Radarr release based on architecture
RUN ARCH=$(dpkg --print-architecture) \
    && DLBASE="https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore" \
    && case "$ARCH" in \
        "amd64") DLURL="${DLBASE}&arch=x64" ;; \
        "armhf") DLURL="${DLBASE}&arch=arm" ;; \
        "arm64") DLURL="${DLBASE}&arch=arm64" ;; \
        *) \
            echo "Architecture non prise en charge: $ARCH" \
            && exit 1 \
            ;; \
        esac \
    && wget --content-disposition "$DLURL" -O radarr.tar.gz \
    && tar -xzf radarr.tar.gz -C /opt/ \
    && chown -R radarr:radarr /opt/Radarr \
    && rm radarr.tar.gz

USER radarr
WORKDIR /opt/Radarr

CMD ["/opt/Radarr/Radarr", "-nobrowser", "-data=/var/lib/radarr"]
